/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ping_CONSTANTS_H
#define ping_CONSTANTS_H

#include "ping_types.h"



class pingConstants {
 public:
  pingConstants();

};

extern const pingConstants g_ping_constants;



#endif
