/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PingService_H
#define PingService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "ping_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class PingServiceIf {
 public:
  virtual ~PingServiceIf() {}
  virtual void ping(std::string& _return) = 0;
  virtual void say(const std::string& msg) = 0;
};

class PingServiceIfFactory {
 public:
  typedef PingServiceIf Handler;

  virtual ~PingServiceIfFactory() {}

  virtual PingServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(PingServiceIf* /* handler */) = 0;
};

class PingServiceIfSingletonFactory : virtual public PingServiceIfFactory {
 public:
  PingServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<PingServiceIf>& iface) : iface_(iface) {}
  virtual ~PingServiceIfSingletonFactory() {}

  virtual PingServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(PingServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<PingServiceIf> iface_;
};

class PingServiceNull : virtual public PingServiceIf {
 public:
  virtual ~PingServiceNull() {}
  void ping(std::string& /* _return */) {
    return;
  }
  void say(const std::string& /* msg */) {
    return;
  }
};


class PingService_ping_args {
 public:

  PingService_ping_args(const PingService_ping_args&);
  PingService_ping_args& operator=(const PingService_ping_args&);
  PingService_ping_args() {
  }

  virtual ~PingService_ping_args() throw();

  bool operator == (const PingService_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const PingService_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PingService_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PingService_ping_pargs {
 public:


  virtual ~PingService_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PingService_ping_result__isset {
  _PingService_ping_result__isset() : success(false) {}
  bool success :1;
} _PingService_ping_result__isset;

class PingService_ping_result {
 public:

  PingService_ping_result(const PingService_ping_result&);
  PingService_ping_result& operator=(const PingService_ping_result&);
  PingService_ping_result() : success() {
  }

  virtual ~PingService_ping_result() throw();
  std::string success;

  _PingService_ping_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const PingService_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const PingService_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PingService_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PingService_ping_presult__isset {
  _PingService_ping_presult__isset() : success(false) {}
  bool success :1;
} _PingService_ping_presult__isset;

class PingService_ping_presult {
 public:


  virtual ~PingService_ping_presult() throw();
  std::string* success;

  _PingService_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _PingService_say_args__isset {
  _PingService_say_args__isset() : msg(false) {}
  bool msg :1;
} _PingService_say_args__isset;

class PingService_say_args {
 public:

  PingService_say_args(const PingService_say_args&);
  PingService_say_args& operator=(const PingService_say_args&);
  PingService_say_args() : msg() {
  }

  virtual ~PingService_say_args() throw();
  std::string msg;

  _PingService_say_args__isset __isset;

  void __set_msg(const std::string& val);

  bool operator == (const PingService_say_args & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const PingService_say_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PingService_say_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PingService_say_pargs {
 public:


  virtual ~PingService_say_pargs() throw();
  const std::string* msg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PingService_say_result {
 public:

  PingService_say_result(const PingService_say_result&);
  PingService_say_result& operator=(const PingService_say_result&);
  PingService_say_result() {
  }

  virtual ~PingService_say_result() throw();

  bool operator == (const PingService_say_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const PingService_say_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PingService_say_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PingService_say_presult {
 public:


  virtual ~PingService_say_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class PingServiceClient : virtual public PingServiceIf {
 public:
  PingServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PingServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(std::string& _return);
  void send_ping();
  void recv_ping(std::string& _return);
  void say(const std::string& msg);
  void send_say(const std::string& msg);
  void recv_say();
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class PingServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<PingServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (PingServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_say(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  PingServiceProcessor(::apache::thrift::stdcxx::shared_ptr<PingServiceIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &PingServiceProcessor::process_ping;
    processMap_["say"] = &PingServiceProcessor::process_say;
  }

  virtual ~PingServiceProcessor() {}
};

class PingServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  PingServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< PingServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< PingServiceIfFactory > handlerFactory_;
};

class PingServiceMultiface : virtual public PingServiceIf {
 public:
  PingServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<PingServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~PingServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<PingServiceIf> > ifaces_;
  PingServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<PingServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping(std::string& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping(_return);
    }
    ifaces_[i]->ping(_return);
    return;
  }

  void say(const std::string& msg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->say(msg);
    }
    ifaces_[i]->say(msg);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class PingServiceConcurrentClient : virtual public PingServiceIf {
 public:
  PingServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PingServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(std::string& _return);
  int32_t send_ping();
  void recv_ping(std::string& _return, const int32_t seqid);
  void say(const std::string& msg);
  int32_t send_say(const std::string& msg);
  void recv_say(const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
